version: "2"
services:
  app:
    container_name: app_escreveai
    restart: always
    image: node:7
    working_dir: /app
    command: npm run dev
    ports:
      - "4000:4000"
    volumes:
        - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo_escreveai
    image: mongo
    ports:
      - "27018:27017"
